# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5717ace56979c45e67d06667f11e6b2ff224fca5ed9f72466b59853118593ddd042ee126d7650c447efbf2d6f90bbc469b6efd7d19000d675f7ddb6d01bf7d76

test:
  secret_key_base: 42e58e4e9f2ca8a89ff4cfc05c31a8d7af7b3acbc314df6ebd5b3239ac94f97c15af42e69cf65e256a0fa93ee0231a850164185e38bbffb5061850b55cea6e26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
